---
title: 'MLTP Data Viz: The Dark Ages'
author: "Jay Shapiro"
date: "7/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(plotly)
library(data.table)

MLTPfiles <- list.files(path = "C:/Users/OneCalledSyn/Desktop/Tagpro/",
                        pattern = "*.tsv", full.names = TRUE)
MLTP_master_stats <- data.frame()
for (lambda in c(1:5)) {
  location <- MLTPfiles[lambda]
  temp <- fread(file = location, 
                sep = "\t", fill = TRUE, header = TRUE) %>% mutate(season = as.factor(lambda + 19))
  
  MLTP_master_stats <- rbind(MLTP_master_stats, temp)
}
#str(MLTP_master_stats)
MLTP_normalized_stats<- mutate(MLTP_master_stats, scpm = score/minutes, success_rate = pm/minutes, tpm = tags/minutes, 
                               poppm = pops/minutes, droppm = drops/minutes, gpm = grabs/minutes,
                               hpm = hold/minutes, cpm = captures/minutes, ppm = prevent/minutes, rpm = returns/minutes,
                               pupm = pups/minutes, kdr = tags/pops, limp = flaccids/minutes, LHpm = longholds/minutes, 
                               handpm = handoff/minutes, GHpm = goodhandoff/minutes, gorepm = goregrab/minutes, corepm = coregrab/minutes,
                               copm = cohandoff/minutes, inbasepm = retinbase/minutes, quickpm = quickret/minutes, savepm = saves/minutes,
                               HApm = holdagainst/minutes, cap_per = (captures/grabs)*100)

MLTP_filtered_stats <- MLTP_normalized_stats %>%
  filter(minutes >= 120) %>%
  select(-c(V28, team)) %>%
    mutate(position = ifelse(ppm > hpm, "Defense", "Offense"))

MLTP_defense_stats <- MLTP_filtered_stats %>%
  filter(ppm > hpm)

MLTP_offense_stats <- MLTP_filtered_stats %>%
  filter(hpm > ppm)

```

```{r echo = FALSE, warning = FALSE, message = FALSE}

write.csv(MLTP_filtered_stats, "C:/Users/OneCalledSyn/Desktop/Tagpro/5304_Combined.csv", row.names = FALSE)
write.csv(MLTP_defense_stats, "C:/Users/OneCalledSyn/Desktop/Tagpro/5304_D.csv", row.names = FALSE)
write.csv(MLTP_offense_stats, "C:/Users/OneCalledSyn/Desktop/Tagpro/5304_O.csv", row.names = FALSE)


```